meta_product_name: "Shotgunz"
meta_title: "Shotgunz - The fastest way to organize with friends!"
meta_description: "Book your spots on your friend's lists and be the first every time! Organising with friends is now easy than ever!"
meta_image: "shotgunz-logo.png"
